/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const Wizard = React.memo(function Wizard(props) {
  // Use React.memo for performance optimization
  const { nodes, materials } = useGLTF("/models/swiss_army_knife.glb");
  // console.log(nodes);

  const modelRef = useRef();

  useFrame((state) => {
    // modelRef.current.position.y =
    //   -1.5 + Math.sin(state.clock.elapsedTime) * 0.35;
  });

  return (
    <group
      {...props}
      dispose={null}
      ref={modelRef}
      position={[0, 0, 0]}
      scale={[0.27, 0.27, 0.27]}
      rotation={[-0.25, 0, 0]}
    >
      {/* Update the mesh references based on your node structure */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry} // Update to the correct geometry
        material={nodes.Object_2.material} // Update to the correct material
        position={[-1.057, 0, 0]}
        rotation={[0, 0.224, 0]}
        scale={0.832}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_3.geometry} // Update to the correct geometry
        material={nodes.Object_3.material} // Update to the correct material
        position={[-1.057, 0, 0]}
        rotation={[0, 0.224, 0]}
        scale={0.832}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry} // Update to the correct geometry
        material={nodes.Object_4.material} // Update to the correct material
        position={[-1.057, 0, 0]}
        rotation={[0, 0.224, 0]}
        scale={0.832}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry} // Update to the correct geometry
        material={nodes.Object_5.material} // Update to the correct material
        position={[-1.057, 0, 0]}
        rotation={[0, 0.224, 0]}
        scale={0.832}
      />
      {/* Add more meshes as needed based on your node structure */}
    </group>
  );
});

export default Wizard;
useGLTF.preload("/models/swiss_army_knife.glb");
